<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd74dfbc9727ce4532999700b6359c1e1
{
    public static $files = array (
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        'a4a119a56e50fbb293281d9a48007e0e' => __DIR__ . '/..' . '/symfony/polyfill-php80/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Php80\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Polyfill\\Ctype\\' => 23,
        ),
        'P' => 
        array (
            'PhpOption\\' => 10,
        ),
        'G' => 
        array (
            'GrahamCampbell\\ResultType\\' => 26,
        ),
        'D' => 
        array (
            'Dotenv\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Php80\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php80',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'PhpOption\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpoption/phpoption/src/PhpOption',
        ),
        'GrahamCampbell\\ResultType\\' => 
        array (
            0 => __DIR__ . '/..' . '/graham-campbell/result-type/src',
        ),
        'Dotenv\\' => 
        array (
            0 => __DIR__ . '/..' . '/vlucas/phpdotenv/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'J' => 
        array (
            'JsonMapper' => 
            array (
                0 => __DIR__ . '/..' . '/netresearch/jsonmapper/src',
            ),
        ),
    );

    public static $classMap = array (
        'Attribute' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Attribute.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Dotenv\\Dotenv' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Dotenv.php',
        'Dotenv\\Exception\\ExceptionInterface' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Exception/ExceptionInterface.php',
        'Dotenv\\Exception\\InvalidEncodingException' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Exception/InvalidEncodingException.php',
        'Dotenv\\Exception\\InvalidFileException' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Exception/InvalidFileException.php',
        'Dotenv\\Exception\\InvalidPathException' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Exception/InvalidPathException.php',
        'Dotenv\\Exception\\ValidationException' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Exception/ValidationException.php',
        'Dotenv\\Loader\\Loader' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Loader/Loader.php',
        'Dotenv\\Loader\\LoaderInterface' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Loader/LoaderInterface.php',
        'Dotenv\\Loader\\Resolver' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Loader/Resolver.php',
        'Dotenv\\Parser\\Entry' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Parser/Entry.php',
        'Dotenv\\Parser\\EntryParser' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Parser/EntryParser.php',
        'Dotenv\\Parser\\Lexer' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Parser/Lexer.php',
        'Dotenv\\Parser\\Lines' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Parser/Lines.php',
        'Dotenv\\Parser\\Parser' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Parser/Parser.php',
        'Dotenv\\Parser\\ParserInterface' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Parser/ParserInterface.php',
        'Dotenv\\Parser\\Value' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Parser/Value.php',
        'Dotenv\\Repository\\AdapterRepository' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/AdapterRepository.php',
        'Dotenv\\Repository\\Adapter\\AdapterInterface' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/AdapterInterface.php',
        'Dotenv\\Repository\\Adapter\\ApacheAdapter' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/ApacheAdapter.php',
        'Dotenv\\Repository\\Adapter\\ArrayAdapter' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/ArrayAdapter.php',
        'Dotenv\\Repository\\Adapter\\EnvConstAdapter' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/EnvConstAdapter.php',
        'Dotenv\\Repository\\Adapter\\GuardedWriter' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/GuardedWriter.php',
        'Dotenv\\Repository\\Adapter\\ImmutableWriter' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/ImmutableWriter.php',
        'Dotenv\\Repository\\Adapter\\MultiReader' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/MultiReader.php',
        'Dotenv\\Repository\\Adapter\\MultiWriter' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/MultiWriter.php',
        'Dotenv\\Repository\\Adapter\\PutenvAdapter' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/PutenvAdapter.php',
        'Dotenv\\Repository\\Adapter\\ReaderInterface' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/ReaderInterface.php',
        'Dotenv\\Repository\\Adapter\\ReplacingWriter' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/ReplacingWriter.php',
        'Dotenv\\Repository\\Adapter\\ServerConstAdapter' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/ServerConstAdapter.php',
        'Dotenv\\Repository\\Adapter\\WriterInterface' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/Adapter/WriterInterface.php',
        'Dotenv\\Repository\\RepositoryBuilder' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/RepositoryBuilder.php',
        'Dotenv\\Repository\\RepositoryInterface' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Repository/RepositoryInterface.php',
        'Dotenv\\Store\\FileStore' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Store/FileStore.php',
        'Dotenv\\Store\\File\\Paths' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Store/File/Paths.php',
        'Dotenv\\Store\\File\\Reader' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Store/File/Reader.php',
        'Dotenv\\Store\\StoreBuilder' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Store/StoreBuilder.php',
        'Dotenv\\Store\\StoreInterface' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Store/StoreInterface.php',
        'Dotenv\\Store\\StringStore' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Store/StringStore.php',
        'Dotenv\\Util\\Regex' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Util/Regex.php',
        'Dotenv\\Util\\Str' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Util/Str.php',
        'Dotenv\\Validator' => __DIR__ . '/..' . '/vlucas/phpdotenv/src/Validator.php',
        'GrahamCampbell\\ResultType\\Error' => __DIR__ . '/..' . '/graham-campbell/result-type/src/Error.php',
        'GrahamCampbell\\ResultType\\Result' => __DIR__ . '/..' . '/graham-campbell/result-type/src/Result.php',
        'GrahamCampbell\\ResultType\\Success' => __DIR__ . '/..' . '/graham-campbell/result-type/src/Success.php',
        'JsonMapper' => __DIR__ . '/..' . '/netresearch/jsonmapper/src/JsonMapper.php',
        'JsonMapper_Exception' => __DIR__ . '/..' . '/netresearch/jsonmapper/src/JsonMapper/Exception.php',
        'PhonePe\\Env' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/Env.php',
        'PhonePe\\common\\configs\\Constants' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/configs/Constants.php',
        'PhonePe\\common\\configs\\Headers' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/configs/Headers.php',
        'PhonePe\\common\\configs\\Instruments' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/configs/Instruments.php',
        'PhonePe\\common\\configs\\MerchantConfig' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/configs/MerchantConfig.php',
        'PhonePe\\common\\configs\\Rails' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/configs/Rails.php',
        'PhonePe\\common\\eventHandler\\Event' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/eventHandler/Event.php',
        'PhonePe\\common\\eventHandler\\EventPublisher' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/eventHandler/EventPublisher.php',
        'PhonePe\\common\\exceptions\\PhonePeException' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/exceptions/PhonePeException.php',
        'PhonePe\\common\\tokenHandler\\OAuthToken' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/tokenHandler/OAuthToken.php',
        'PhonePe\\common\\tokenHandler\\TokenService' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/tokenHandler/TokenService.php',
        'PhonePe\\common\\utils\\CurlHttpClient' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/utils/CurlHttpClient.php',
        'PhonePe\\common\\utils\\HttpRequest' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/utils/HttpRequest.php',
        'PhonePe\\common\\utils\\HttpResponse' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/common/utils/HttpResponse.php',
        'PhonePe\\payments\\v2\\models\\request\\StandardCheckoutPayRequest' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/request/StandardCheckoutPayRequest.php',
        'PhonePe\\payments\\v2\\models\\request\\StandardCheckoutRefundRequest' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/request/StandardCheckoutRefundRequest.php',
        'PhonePe\\payments\\v2\\models\\request\\builders\\StandardCheckoutPayRequestBuilder' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/request/builders/StandardCheckoutPayRequestBuilder.php',
        'PhonePe\\payments\\v2\\models\\request\\builders\\StandardCheckoutRefundRequestBuilder' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/request/builders/StandardCheckoutRefundRequestBuilder.php',
        'PhonePe\\payments\\v2\\models\\response\\CallbackResponse' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/CallbackResponse.php',
        'PhonePe\\payments\\v2\\models\\response\\RefundStatusCheckResponse' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/RefundStatusCheckResponse.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\AccountInstrument' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/AccountInstrument.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\CreditCardInstrument' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/CreditCardInstrument.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\CreditLinePaymentInstrument' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/CreditLinePaymentInstrument.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\DebitCardInstrument' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/DebitCardInstrument.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\EgvPaymentInstrument' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/EgvPaymentInstrument.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\Instrument' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/Instrument.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\MetaInfo' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/MetaInfo.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\NetBankingInstrument' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/NetBankingInstrument.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\Payload' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/Payload.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\PaymentDetail' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/PaymentDetail.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\PgRail' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/PgRail.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\PpiEgvRail' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/PpiEgvRail.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\PpiWalletRail' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/PpiWalletRail.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\Rail' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/Rail.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\UpiRail' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/UpiRail.php',
        'PhonePe\\payments\\v2\\models\\response\\ResponseComponents\\WalletPaymentInstrument' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/ResponseComponents/WalletPaymentInstrument.php',
        'PhonePe\\payments\\v2\\models\\response\\StandardCheckoutPayResponse' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/StandardCheckoutPayResponse.php',
        'PhonePe\\payments\\v2\\models\\response\\StandardCheckoutRefundResponse' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/StandardCheckoutRefundResponse.php',
        'PhonePe\\payments\\v2\\models\\response\\StatusCheckResponse' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/models/response/StatusCheckResponse.php',
        'PhonePe\\payments\\v2\\standardCheckout\\StandardCheckoutClient' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/standardCheckout/StandardCheckoutClient.php',
        'PhonePe\\payments\\v2\\standardCheckout\\StandardCheckoutConstants' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/src/phonepe/sdk/pg/payments/v2/standardCheckout/StandardCheckoutConstants.php',
        'PhpOption\\LazyOption' => __DIR__ . '/..' . '/phpoption/phpoption/src/PhpOption/LazyOption.php',
        'PhpOption\\None' => __DIR__ . '/..' . '/phpoption/phpoption/src/PhpOption/None.php',
        'PhpOption\\Option' => __DIR__ . '/..' . '/phpoption/phpoption/src/PhpOption/Option.php',
        'PhpOption\\Some' => __DIR__ . '/..' . '/phpoption/phpoption/src/PhpOption/Some.php',
        'PhpToken' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/PhpToken.php',
        'Stringable' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Stringable.php',
        'Symfony\\Polyfill\\Ctype\\Ctype' => __DIR__ . '/..' . '/symfony/polyfill-ctype/Ctype.php',
        'Symfony\\Polyfill\\Mbstring\\Mbstring' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/Mbstring.php',
        'Symfony\\Polyfill\\Php80\\Php80' => __DIR__ . '/..' . '/symfony/polyfill-php80/Php80.php',
        'Symfony\\Polyfill\\Php80\\PhpToken' => __DIR__ . '/..' . '/symfony/polyfill-php80/PhpToken.php',
        'UnhandledMatchError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php',
        'Unit\\EnvTest' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/tests/Unit/EnvTest.php',
        'Unit\\common\\TokenHandler\\TokenServiceTest' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/tests/Unit/common/TokenHandler/TokenServiceTest.php',
        'Unit\\common\\utils\\HttpRequestTest' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/tests/Unit/common/utils/HttpRequestTest.php',
        'Unit\\common\\utils\\RequestGeneratorTest' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/tests/Unit/common/utils/RequestGeneratorTest.php',
        'Unit\\payments\\v2\\standardCheckout\\StandardCheckoutClientTest' => __DIR__ . '/..' . '/phonepe/pg-php-sdk-v2/tests/Unit/payments/v2/standardCheckout/StandardCheckoutClientTest.php',
        'ValueError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/ValueError.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd74dfbc9727ce4532999700b6359c1e1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd74dfbc9727ce4532999700b6359c1e1::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitd74dfbc9727ce4532999700b6359c1e1::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitd74dfbc9727ce4532999700b6359c1e1::$classMap;

        }, null, ClassLoader::class);
    }
}
